"""Pulse characteristics calculator for SHPB analysis.

Computes theoretical pulse properties from striker geometry and bar material
properties. These values characterize the expected stress pulse before
detection and are stored on the SHPBCompression test instance.

Classes
-------
PulseCharacteristicsResult : Dataclass holding computed pulse properties
PulseCharacteristics : Calculator for theoretical pulse parameters

References
----------
Gray, G. T. (2000). Classic Split-Hopkinson Pressure Bar Testing.
ASM Handbook, Vol. 8: Mechanical Testing and Evaluation.

Chen, W. W., & Song, B. (2011). Split Hopkinson (Kolsky) Bar: Design,
Testing and Applications. Springer.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PulseCharacteristicsResult:
    """Computed theoretical pulse characteristics.

    All values are derived from striker geometry, bar material properties,
    and striker impact velocity.

    Attributes
    ----------
    pulse_duration_ms : float
        Theoretical pulse duration in milliseconds (2L/C).
    pulse_length_mm : float
        Physical length of the stress pulse in the bar (2L) in mm.
    pulse_speed_m_s : float
        Propagation speed of the stress pulse (bar wave speed C) in m/s.
    pulse_strain_amplitude : float
        Maximum strain amplitude of the incident pulse (V/2C), unitless.
    pulse_stress_amplitude_mpa : float
        Maximum stress amplitude of the incident pulse (rho*C*V/2) in MPa.
    pulse_points : int
        Expected pulse duration in samples (duration / dt).
    """

    pulse_duration_ms: float
    pulse_length_mm: float
    pulse_speed_m_s: float
    pulse_strain_amplitude: float
    pulse_stress_amplitude_mpa: float
    pulse_points: int

    def to_dict(self) -> dict:
        """Convert to dictionary for state storage.

        Returns
        -------
        dict
            Keys match attribute names.
        """
        return {
            'pulse_duration': self.pulse_duration_ms,
            'pulse_length': self.pulse_length_mm,
            'pulse_speed': self.pulse_speed_m_s,
            'pulse_strain_amplitude': self.pulse_strain_amplitude,
            'pulse_stress_amplitude': self.pulse_stress_amplitude_mpa,
            'pulse_points': self.pulse_points,
        }


class PulseCharacteristics:
    """Calculate theoretical pulse properties from striker and bar parameters.

    The stress pulse generated by striker impact has predictable properties
    based on the striker geometry and bar material. These theoretical values
    are used to configure pulse detection (expected window size) and to
    characterize the test conditions.

    Parameters
    ----------
    striker_length_mm : float
        Length of the striker bar in millimeters.
    bar_wave_speed_m_s : float
        Longitudinal wave speed in the bar material in m/s.
    bar_density_kg_m3 : float
        Density of the bar material in kg/m^3.

    Examples
    --------
    >>> calc = PulseCharacteristics(
    ...     striker_length_mm=457.2,
    ...     bar_wave_speed_m_s=4953.3,
    ...     bar_density_kg_m3=8050.0
    ... )
    >>> result = calc.calculate(striker_velocity_m_s=25.22, sampling_interval_ms=0.0125)
    >>> print(f"Duration: {result.pulse_duration_ms:.4f} ms")
    Duration: 0.1846 ms
    >>> print(f"Points: {result.pulse_points}")
    Points: 14768
    """

    def __init__(
        self,
        striker_length_mm: float,
        bar_wave_speed_m_s: float,
        bar_density_kg_m3: float,
    ):
        if striker_length_mm <= 0:
            raise ValueError(f"striker_length_mm must be positive, got {striker_length_mm}")
        if bar_wave_speed_m_s <= 0:
            raise ValueError(f"bar_wave_speed_m_s must be positive, got {bar_wave_speed_m_s}")
        if bar_density_kg_m3 <= 0:
            raise ValueError(f"bar_density_kg_m3 must be positive, got {bar_density_kg_m3}")

        self.striker_length_mm = striker_length_mm
        self.bar_wave_speed_m_s = bar_wave_speed_m_s
        self.bar_density_kg_m3 = bar_density_kg_m3

    def calculate(
        self,
        striker_velocity_m_s: float,
        sampling_interval_ms: float,
    ) -> PulseCharacteristicsResult:
        """Compute theoretical pulse characteristics.

        Parameters
        ----------
        striker_velocity_m_s : float
            Impact velocity of the striker bar in m/s.
        sampling_interval_ms : float
            Time between consecutive data samples in milliseconds.

        Returns
        -------
        PulseCharacteristicsResult
            Computed pulse properties.

        Raises
        ------
        ValueError
            If striker_velocity_m_s or sampling_interval_ms are not positive.
        """
        if striker_velocity_m_s <= 0:
            raise ValueError(f"striker_velocity_m_s must be positive, got {striker_velocity_m_s}")
        if sampling_interval_ms <= 0:
            raise ValueError(f"sampling_interval_ms must be positive, got {sampling_interval_ms}")

        C = self.bar_wave_speed_m_s
        L = self.striker_length_mm
        rho = self.bar_density_kg_m3
        V = striker_velocity_m_s

        # Pulse duration: T = 2L/C  (striker length in mm, wave speed in m/s → ms)
        pulse_duration_ms = (2.0 * L) / C

        # Pulse spatial length: 2L (mm)
        pulse_length_mm = 2.0 * L

        # Pulse speed: bar wave speed (m/s)
        pulse_speed_m_s = C

        # Strain amplitude: epsilon_i = V / (2C)  (unitless)
        pulse_strain_amplitude = 0.5 * (V / C)

        # Stress amplitude: sigma_i = rho * C * V / 2  (Pa → MPa via /1e6)
        # rho [kg/m^3] * C [m/s] * V [m/s] = [Pa]
        pulse_stress_amplitude_mpa = (0.5 * rho * C * V) / 1e6

        # Pulse points: duration / sampling interval
        pulse_points = int(pulse_duration_ms / sampling_interval_ms)

        result = PulseCharacteristicsResult(
            pulse_duration_ms=pulse_duration_ms,
            pulse_length_mm=pulse_length_mm,
            pulse_speed_m_s=pulse_speed_m_s,
            pulse_strain_amplitude=pulse_strain_amplitude,
            pulse_stress_amplitude_mpa=pulse_stress_amplitude_mpa,
            pulse_points=pulse_points,
        )

        logger.info(
            f"Pulse characteristics: duration={pulse_duration_ms:.4f} ms, "
            f"points={pulse_points}, stress_amp={pulse_stress_amplitude_mpa:.1f} MPa"
        )

        return result

    def __repr__(self) -> str:
        return (
            f"PulseCharacteristics(striker_length_mm={self.striker_length_mm}, "
            f"bar_wave_speed_m_s={self.bar_wave_speed_m_s}, "
            f"bar_density_kg_m3={self.bar_density_kg_m3})"
        )
